# Generated by Django 5.2.7 on 2026-03-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(choices=[('Grocery', 'Grocery'), ('Snacks', 'Snacks'), ('Food', 'Food'), ('Travel', 'Travel'), ('Recharge', 'Recharge'), ('Monthly', 'Monthly')], max_length=20),
        ),
    ]
